version: '3'
services:
  ui:
    build:
      context: ui/.
    tty: true
    volumes:
      - ./ui/dist:/var/www/html
      - ./ui/nginx/conf.d:/etc/nginx/conf.d
    ports:
    - 80:80
  api:
    build: api/.
    depends_on:
    - db
    volumes:
    - ./api:/code
    ports:
    - 8000:8000
  db:
    restart: always
    image: mysql:latest
    volumes:
    - ./mysql:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=pass_word
    - MYSQL_DATABASE=metaweb
    ports:
    - 3306:3306
